import { Proposal, ProposalStats } from "./types";

export const mockProposals: Proposal[] = [
  {
    id: "1",
    proposalNumber: "PROP-2024-001",
    accountName: "Blum Oakland",
    contactName: "Sarah Johnson",
    status: "Approved",
    totalAmount: 15250.00,
    proposalDate: "2024-10-20",
    expirationDate: "2024-12-20",
    description: "Q1 2025 Product Line Expansion Proposal",
    productCount: 12,
    opportunityName: "Q1 2025 Growth Initiative",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "2",
    proposalNumber: "PROP-2024-002",
    accountName: "Green Valley Dispensary",
    contactName: "Michael Chen",
    status: "Pending Review",
    totalAmount: 8900.50,
    proposalDate: "2024-11-15",
    expirationDate: "2024-12-15",
    description: "Holiday Season Premium Product Selection",
    productCount: 8,
    opportunityName: "Holiday Sales 2024",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "3",
    proposalNumber: "PROP-2024-003",
    accountName: "Urban Wellness Co.",
    contactName: "Jessica Martinez",
    status: "Under Review",
    totalAmount: 22100.75,
    proposalDate: "2024-11-10",
    expirationDate: "2025-01-10",
    description: "New Store Opening - Complete Product Suite",
    productCount: 18,
    opportunityName: "Downtown Location Launch",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "4",
    proposalNumber: "PROP-2024-004",
    accountName: "Natural Remedies SF",
    contactName: "David Kim",
    status: "Accepted",
    totalAmount: 12800.00,
    proposalDate: "2024-10-05",
    expirationDate: "2024-12-05",
    description: "Premium Concentrate Line Introduction",
    productCount: 10,
    opportunityName: "Concentrates Expansion",
    submittedBy: "Account Manager - Sarah Lee"
  },
  {
    id: "5",
    proposalNumber: "PROP-2024-005",
    accountName: "Wellness Works",
    contactName: "Amanda Foster",
    status: "Rejected",
    totalAmount: 6500.25,
    proposalDate: "2024-09-20",
    expirationDate: "2024-11-20",
    description: "Trial Product Sampling Program",
    productCount: 6,
    opportunityName: "New Vendor Evaluation",
    submittedBy: "Sales Rep - Mike Johnson"
  },
  {
    id: "6",
    proposalNumber: "PROP-2024-006",
    accountName: "Therapeutic Gardens",
    contactName: "Robert Taylor",
    status: "Draft",
    totalAmount: 18400.00,
    proposalDate: "2024-11-18",
    expirationDate: "2025-01-18",
    description: "Winter Collection - Premium Flower Selection",
    productCount: 14,
    opportunityName: "Winter Season 2024",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "7",
    proposalNumber: "PROP-2024-007",
    accountName: "Blum San Francisco",
    contactName: "Lisa Anderson",
    status: "Approved",
    totalAmount: 25600.50,
    proposalDate: "2024-10-25",
    expirationDate: "2024-12-25",
    description: "Year-End Inventory Expansion Package",
    productCount: 20,
    opportunityName: "Year-End Stock Build",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "8",
    proposalNumber: "PROP-2024-008",
    accountName: "Harmony Health",
    contactName: "Christopher Lee",
    status: "Pending Review",
    totalAmount: 9250.00,
    proposalDate: "2024-11-12",
    expirationDate: "2025-01-12",
    description: "Monthly Subscription Service Proposal",
    productCount: 7,
    opportunityName: "Subscription Program Launch",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "9",
    proposalNumber: "PROP-2024-009",
    accountName: "Pure Wellness Market",
    contactName: "Emily White",
    status: "Expired",
    totalAmount: 16200.00,
    proposalDate: "2024-08-15",
    expirationDate: "2024-10-15",
    description: "Vaporizer and Concentrate Bundle",
    productCount: 11,
    opportunityName: "Product Line Diversification",
    submittedBy: "Account Manager - Sarah Lee"
  },
  {
    id: "10",
    proposalNumber: "PROP-2024-010",
    accountName: "Green Leaf Collective",
    contactName: "James Wilson",
    status: "Accepted",
    totalAmount: 19750.25,
    proposalDate: "2024-10-15",
    expirationDate: "2024-12-15",
    description: "Multi-Location Distribution Agreement",
    productCount: 16,
    opportunityName: "3-Store Expansion",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "11",
    proposalNumber: "PROP-2024-011",
    accountName: "Elevated Dispensary",
    contactName: "Patricia Brown",
    status: "Under Review",
    totalAmount: 11100.75,
    proposalDate: "2024-11-08",
    expirationDate: "2025-01-08",
    description: "Premium Pre-Roll Collection Launch",
    productCount: 9,
    opportunityName: "Premium Product Line",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "12",
    proposalNumber: "PROP-2024-012",
    accountName: "Coastal Cannabis Co.",
    contactName: "Daniel Moore",
    status: "Approved",
    totalAmount: 17400.00,
    proposalDate: "2024-10-18",
    expirationDate: "2024-12-18",
    description: "Bulk Purchase Agreement - Edibles Focus",
    productCount: 13,
    opportunityName: "Bulk Purchase Program",
    submittedBy: "Sales Rep - Mike Johnson"
  },
  {
    id: "13",
    proposalNumber: "PROP-2024-013",
    accountName: "Mountain View Wellness",
    contactName: "Karen Davis",
    status: "Draft",
    totalAmount: 7800.50,
    proposalDate: "2024-11-16",
    expirationDate: "2025-01-16",
    description: "Topicals and Wellness Product Introduction",
    productCount: 5,
    opportunityName: "Wellness Category Entry",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "14",
    proposalNumber: "PROP-2024-014",
    accountName: "Sunset Remedies",
    contactName: "Steven Garcia",
    status: "Accepted",
    totalAmount: 23500.00,
    proposalDate: "2024-10-10",
    expirationDate: "2024-12-10",
    description: "Holiday Premium Selection Package",
    productCount: 17,
    opportunityName: "Holiday Premium 2024",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "15",
    proposalNumber: "PROP-2024-015",
    accountName: "Organic Options",
    contactName: "Michelle Rodriguez",
    status: "Pending Review",
    totalAmount: 13300.25,
    proposalDate: "2024-11-14",
    expirationDate: "2025-01-14",
    description: "Organic Certified Product Line Proposal",
    productCount: 10,
    opportunityName: "Organic Line Launch",
    submittedBy: "Account Manager - Sarah Lee"
  },
  {
    id: "16",
    proposalNumber: "PROP-2024-016",
    accountName: "Valley Green Dispensary",
    contactName: "Thomas Martinez",
    status: "Expired",
    totalAmount: 9800.00,
    proposalDate: "2024-08-10",
    expirationDate: "2024-10-10",
    description: "Fall Special Product Collection",
    productCount: 8,
    opportunityName: "Fall Season 2024",
    submittedBy: "Sales Rep - Mike Johnson"
  },
  {
    id: "17",
    proposalNumber: "PROP-2024-017",
    accountName: "Pacific Wellness Group",
    contactName: "Jennifer Lopez",
    status: "Under Review",
    totalAmount: 28900.00,
    proposalDate: "2024-11-05",
    expirationDate: "2025-01-05",
    description: "Corporate Group Purchase Agreement",
    productCount: 22,
    opportunityName: "4-Location Group Deal",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "18",
    proposalNumber: "PROP-2024-018",
    accountName: "Healing Gardens",
    contactName: "Brian Taylor",
    status: "Approved",
    totalAmount: 14750.50,
    proposalDate: "2024-10-22",
    expirationDate: "2024-12-22",
    description: "Concentrate Expansion Proposal",
    productCount: 11,
    opportunityName: "Concentrates Focus",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "19",
    proposalNumber: "PROP-2024-019",
    accountName: "Verde Solutions",
    contactName: "Angela Harris",
    status: "Pending Review",
    totalAmount: 10900.00,
    proposalDate: "2024-11-11",
    expirationDate: "2025-01-11",
    description: "Recurring Delivery Service Agreement",
    productCount: 8,
    opportunityName: "Subscription Service",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "20",
    proposalNumber: "PROP-2024-020",
    accountName: "Emerald Collective",
    contactName: "Mark Thompson",
    status: "Accepted",
    totalAmount: 21250.75,
    proposalDate: "2024-10-28",
    expirationDate: "2024-12-28",
    description: "Full Product Line Annual Agreement",
    productCount: 19,
    opportunityName: "Annual Supply Contract",
    submittedBy: "Regional Manager - Bob Wilson"
  }
];

export const mockProposalStats: ProposalStats = {
  totalProposals: 20,
  pendingReview: 4,
  approvedProposals: 5,
  totalValue: 316350.00
};
