import { Proposal, ProposalStats } from "./types";

export const mockProposals: Proposal[] = [
  {
    id: "1",
    proposalNumber: "PROP-2024-001",
    proposalName: "Q1 2025 Product Line Expansion",
    accountName: "Blum Oakland",
    contactName: "Sarah Johnson",
    status: "Approved",
    totalAmount: 15250.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-20",
    expirationDate: "2024-12-20",
    description: "Q1 2025 Product Line Expansion Proposal",
    productCount: 12,
    billTo: "Blum Oakland - 578 West Grand Ave, Oakland, CA 94612",
    shipTo: "Blum Oakland - 578 West Grand Ave, Oakland, CA 94612",
    opportunityName: "Q1 2025 Growth Initiative",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "2",
    proposalNumber: "PROP-2024-002",
    proposalName: "Holiday Season Premium Selection",
    accountName: "Green Valley Dispensary",
    contactName: "Michael Chen",
    status: "Pending Review",
    totalAmount: 8900.50,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-15",
    expirationDate: "2024-12-15",
    description: "Holiday Season Premium Product Selection",
    productCount: 8,
    billTo: "Green Valley Dispensary - 123 Main St, San Jose, CA 95112",
    shipTo: "Green Valley Warehouse - 456 Industrial Blvd, San Jose, CA 95113",
    opportunityName: "Holiday Sales 2024",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "3",
    proposalNumber: "PROP-2024-003",
    proposalName: "New Store Opening Package",
    accountName: "Urban Wellness Co.",
    contactName: "Jessica Martinez",
    status: "Under Review",
    totalAmount: 22100.75,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-10",
    expirationDate: "2025-01-10",
    description: "New Store Opening - Complete Product Suite",
    productCount: 18,
    billTo: "Urban Wellness Co. - 890 Market St, San Francisco, CA 94102",
    shipTo: "Urban Wellness Downtown - 100 Powell St, San Francisco, CA 94103",
    opportunityName: "Downtown Location Launch",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "4",
    proposalNumber: "PROP-2024-004",
    proposalName: "Premium Concentrate Line",
    accountName: "Natural Remedies SF",
    contactName: "David Kim",
    status: "Accepted",
    totalAmount: 12800.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-05",
    expirationDate: "2024-12-05",
    description: "Premium Concentrate Line Introduction",
    productCount: 10,
    billTo: "Natural Remedies SF - 200 Valencia St, San Francisco, CA 94103",
    shipTo: "Natural Remedies SF - 200 Valencia St, San Francisco, CA 94103",
    opportunityName: "Concentrates Expansion",
    submittedBy: "Account Manager - Sarah Lee"
  },
  {
    id: "5",
    proposalNumber: "PROP-2024-005",
    proposalName: "Trial Sampling Program",
    accountName: "Wellness Works",
    contactName: "Amanda Foster",
    status: "Rejected",
    totalAmount: 6500.25,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-09-20",
    expirationDate: "2024-11-20",
    description: "Trial Product Sampling Program",
    productCount: 6,
    billTo: "Wellness Works - 555 Howard St, San Francisco, CA 94105",
    shipTo: "Wellness Works - 555 Howard St, San Francisco, CA 94105",
    opportunityName: "New Vendor Evaluation",
    submittedBy: "Sales Rep - Mike Johnson"
  },
  {
    id: "6",
    proposalNumber: "PROP-2024-006",
    proposalName: "Winter Collection Premium",
    accountName: "Therapeutic Gardens",
    contactName: "Robert Taylor",
    status: "Draft",
    totalAmount: 18400.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-18",
    expirationDate: "2025-01-18",
    description: "Winter Collection - Premium Flower Selection",
    productCount: 14,
    billTo: "Therapeutic Gardens - 789 Broadway, Oakland, CA 94607",
    shipTo: "Therapeutic Gardens - 789 Broadway, Oakland, CA 94607",
    opportunityName: "Winter Season 2024",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "7",
    proposalNumber: "PROP-2024-007",
    proposalName: "Year-End Inventory Expansion",
    accountName: "Blum San Francisco",
    contactName: "Lisa Anderson",
    status: "Approved",
    totalAmount: 25600.50,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-25",
    expirationDate: "2024-12-25",
    description: "Year-End Inventory Expansion Package",
    productCount: 20,
    billTo: "Blum San Francisco - 350 Mission St, San Francisco, CA 94105",
    shipTo: "Blum SF Distribution - 1200 Brannan St, San Francisco, CA 94103",
    opportunityName: "Year-End Stock Build",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "8",
    proposalNumber: "PROP-2024-008",
    proposalName: "Monthly Subscription Service",
    accountName: "Harmony Health",
    contactName: "Christopher Lee",
    status: "Pending Review",
    totalAmount: 9250.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-12",
    expirationDate: "2025-01-12",
    description: "Monthly Subscription Service Proposal",
    productCount: 7,
    billTo: "Harmony Health - 425 Castro St, San Francisco, CA 94114",
    shipTo: "Harmony Health - 425 Castro St, San Francisco, CA 94114",
    opportunityName: "Subscription Program Launch",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "9",
    proposalNumber: "PROP-2024-009",
    proposalName: "Vaporizer & Concentrate Bundle",
    accountName: "Pure Wellness Market",
    contactName: "Emily White",
    status: "Expired",
    totalAmount: 16200.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-08-15",
    expirationDate: "2024-10-15",
    description: "Vaporizer and Concentrate Bundle",
    productCount: 11,
    billTo: "Pure Wellness Market - 600 Geary St, San Francisco, CA 94102",
    shipTo: "Pure Wellness Market - 600 Geary St, San Francisco, CA 94102",
    opportunityName: "Product Line Diversification",
    submittedBy: "Account Manager - Sarah Lee"
  },
  {
    id: "10",
    proposalNumber: "PROP-2024-010",
    proposalName: "Multi-Location Distribution",
    accountName: "Green Leaf Collective",
    contactName: "James Wilson",
    status: "Accepted",
    totalAmount: 19750.25,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-15",
    expirationDate: "2024-12-15",
    description: "Multi-Location Distribution Agreement",
    productCount: 16,
    billTo: "Green Leaf Collective HQ - 1500 Folsom St, San Francisco, CA 94103",
    shipTo: "Green Leaf Distribution - 2000 Army St, San Francisco, CA 94124",
    opportunityName: "3-Store Expansion",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "11",
    proposalNumber: "PROP-2024-011",
    proposalName: "Premium Pre-Roll Collection",
    accountName: "Elevated Dispensary",
    contactName: "Patricia Brown",
    status: "Under Review",
    totalAmount: 11100.75,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-08",
    expirationDate: "2025-01-08",
    description: "Premium Pre-Roll Collection Launch",
    productCount: 9,
    billTo: "Elevated Dispensary - 750 Haight St, San Francisco, CA 94117",
    shipTo: "Elevated Dispensary - 750 Haight St, San Francisco, CA 94117",
    opportunityName: "Premium Product Line",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "12",
    proposalNumber: "PROP-2024-012",
    proposalName: "Bulk Purchase - Edibles",
    accountName: "Coastal Cannabis Co.",
    contactName: "Daniel Moore",
    status: "Approved",
    totalAmount: 17400.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-18",
    expirationDate: "2024-12-18",
    description: "Bulk Purchase Agreement - Edibles Focus",
    productCount: 13,
    billTo: "Coastal Cannabis Co. - 1800 Ocean Ave, San Francisco, CA 94112",
    shipTo: "Coastal Cannabis Warehouse - 300 Industrial Way, South SF, CA 94080",
    opportunityName: "Bulk Purchase Program",
    submittedBy: "Sales Rep - Mike Johnson"
  },
  {
    id: "13",
    proposalNumber: "PROP-2024-013",
    proposalName: "Topicals & Wellness Products",
    accountName: "Mountain View Wellness",
    contactName: "Karen Davis",
    status: "Draft",
    totalAmount: 7800.50,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-16",
    expirationDate: "2025-01-16",
    description: "Topicals and Wellness Product Introduction",
    productCount: 5,
    billTo: "Mountain View Wellness - 900 El Camino Real, Mountain View, CA 94040",
    shipTo: "Mountain View Wellness - 900 El Camino Real, Mountain View, CA 94040",
    opportunityName: "Wellness Category Entry",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "14",
    proposalNumber: "PROP-2024-014",
    proposalName: "Holiday Premium Selection",
    accountName: "Sunset Remedies",
    contactName: "Steven Garcia",
    status: "Accepted",
    totalAmount: 23500.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-10",
    expirationDate: "2024-12-10",
    description: "Holiday Premium Selection Package",
    productCount: 17,
    billTo: "Sunset Remedies - 2400 Irving St, San Francisco, CA 94122",
    shipTo: "Sunset Remedies - 2400 Irving St, San Francisco, CA 94122",
    opportunityName: "Holiday Premium 2024",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "15",
    proposalNumber: "PROP-2024-015",
    proposalName: "Organic Certified Products",
    accountName: "Organic Options",
    contactName: "Michelle Rodriguez",
    status: "Pending Review",
    totalAmount: 13300.25,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-14",
    expirationDate: "2025-01-14",
    description: "Organic Certified Product Line Proposal",
    productCount: 10,
    billTo: "Organic Options - 1100 University Ave, Berkeley, CA 94702",
    shipTo: "Organic Options - 1100 University Ave, Berkeley, CA 94702",
    opportunityName: "Organic Line Launch",
    submittedBy: "Account Manager - Sarah Lee"
  },
  {
    id: "16",
    proposalNumber: "PROP-2024-016",
    proposalName: "Fall Special Collection",
    accountName: "Valley Green Dispensary",
    contactName: "Thomas Martinez",
    status: "Expired",
    totalAmount: 9800.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-08-10",
    expirationDate: "2024-10-10",
    description: "Fall Special Product Collection",
    productCount: 8,
    billTo: "Valley Green Dispensary - 500 San Antonio Rd, Palo Alto, CA 94306",
    shipTo: "Valley Green Dispensary - 500 San Antonio Rd, Palo Alto, CA 94306",
    opportunityName: "Fall Season 2024",
    submittedBy: "Sales Rep - Mike Johnson"
  },
  {
    id: "17",
    proposalNumber: "PROP-2024-017",
    proposalName: "Corporate Group Purchase",
    accountName: "Pacific Wellness Group",
    contactName: "Jennifer Lopez",
    status: "Under Review",
    totalAmount: 28900.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-05",
    expirationDate: "2025-01-05",
    description: "Corporate Group Purchase Agreement",
    productCount: 22,
    billTo: "Pacific Wellness Group HQ - 100 California St, San Francisco, CA 94111",
    shipTo: "Pacific Wellness Distribution - 800 3rd St, San Francisco, CA 94107",
    opportunityName: "4-Location Group Deal",
    submittedBy: "Regional Manager - Bob Wilson"
  },
  {
    id: "18",
    proposalNumber: "PROP-2024-018",
    proposalName: "Concentrate Expansion",
    accountName: "Healing Gardens",
    contactName: "Brian Taylor",
    status: "Approved",
    totalAmount: 14750.50,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-22",
    expirationDate: "2024-12-22",
    description: "Concentrate Expansion Proposal",
    productCount: 11,
    billTo: "Healing Gardens - 1600 Fillmore St, San Francisco, CA 94115",
    shipTo: "Healing Gardens - 1600 Fillmore St, San Francisco, CA 94115",
    opportunityName: "Concentrates Focus",
    submittedBy: "Account Manager - John Doe"
  },
  {
    id: "19",
    proposalNumber: "PROP-2024-019",
    proposalName: "Recurring Delivery Service",
    accountName: "Verde Solutions",
    contactName: "Angela Harris",
    status: "Pending Review",
    totalAmount: 10900.00,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-11-11",
    expirationDate: "2025-01-11",
    description: "Recurring Delivery Service Agreement",
    productCount: 8,
    billTo: "Verde Solutions - 2200 Van Ness Ave, San Francisco, CA 94109",
    shipTo: "Verde Solutions - 2200 Van Ness Ave, San Francisco, CA 94109",
    opportunityName: "Subscription Service",
    submittedBy: "Sales Rep - Jane Smith"
  },
  {
    id: "20",
    proposalNumber: "PROP-2024-020",
    proposalName: "Full Product Line Annual",
    accountName: "Emerald Collective",
    contactName: "Mark Thompson",
    status: "Accepted",
    totalAmount: 21250.75,
    totalShippingCharges: 0,
    totalTaxesAmount: 0,
    proposalDate: "2024-10-28",
    expirationDate: "2024-12-28",
    description: "Full Product Line Annual Agreement",
    productCount: 19,
    billTo: "Emerald Collective - 3000 16th St, San Francisco, CA 94103",
    shipTo: "Emerald Collective Distribution - 450 Bayshore Blvd, San Francisco, CA 94124",
    opportunityName: "Annual Supply Contract",
    submittedBy: "Regional Manager - Bob Wilson"
  }
];

export const mockProposalStats: ProposalStats = {
  totalProposals: 20,
  pendingReview: 4,
  approvedProposals: 5,
  totalValue: 316350.00
};
