import { Quote, QuoteStats } from "./types";

export const mockQuotes: Quote[] = [
  {
    id: "1",
    quoteNumber: "Q-2024-001",
    accountName: "Blum Oakland",
    contactName: "Sarah Johnson",
    status: "Approved",
    totalAmount: 12500.00,
    validUntil: "2024-12-31",
    createdDate: "2024-11-15",
    description: "Q4 2024 Product Order - Premium Selection",
    lineItemCount: 8,
    opportunityName: "Q4 2024 Expansion"
  },
  {
    id: "2",
    quoteNumber: "Q-2024-002",
    accountName: "Green Valley Dispensary",
    contactName: "Michael Chen",
    status: "Pending",
    totalAmount: 8750.50,
    validUntil: "2024-12-15",
    createdDate: "2024-11-18",
    description: "Holiday Season Stock - Edibles Focus",
    lineItemCount: 5,
    opportunityName: "Holiday Sales 2024"
  },
  {
    id: "3",
    quoteNumber: "Q-2024-003",
    accountName: "Urban Wellness Co.",
    contactName: "Jessica Martinez",
    status: "Draft",
    totalAmount: 15200.75,
    validUntil: "2024-12-20",
    createdDate: "2024-11-20",
    description: "New Store Opening - Initial Stock",
    lineItemCount: 12,
    opportunityName: "New Location - Downtown"
  },
  {
    id: "4",
    quoteNumber: "Q-2024-004",
    accountName: "Natural Remedies SF",
    contactName: "David Kim",
    status: "Converted",
    totalAmount: 9800.00,
    validUntil: "2024-11-30",
    createdDate: "2024-10-28",
    description: "Monthly Restock - Standard Mix",
    lineItemCount: 6,
    opportunityName: "November Restock"
  },
  {
    id: "5",
    quoteNumber: "Q-2024-005",
    accountName: "Wellness Works",
    contactName: "Amanda Foster",
    status: "Rejected",
    totalAmount: 5600.25,
    validUntil: "2024-11-25",
    createdDate: "2024-10-15",
    description: "Trial Order - Sample Products",
    lineItemCount: 4,
    opportunityName: "New Vendor Trial"
  },
  {
    id: "6",
    quoteNumber: "Q-2024-006",
    accountName: "Therapeutic Gardens",
    contactName: "Robert Taylor",
    status: "Expired",
    totalAmount: 11300.00,
    validUntil: "2024-11-15",
    createdDate: "2024-10-01",
    description: "Fall Collection - Premium Flower",
    lineItemCount: 7,
    opportunityName: "Fall Collection 2024"
  },
  {
    id: "7",
    quoteNumber: "Q-2024-007",
    accountName: "Blum San Francisco",
    contactName: "Lisa Anderson",
    status: "Approved",
    totalAmount: 18900.50,
    validUntil: "2024-12-28",
    createdDate: "2024-11-22",
    description: "Year-End Inventory Buildup",
    lineItemCount: 15,
    opportunityName: "Year-End Stock"
  },
  {
    id: "8",
    quoteNumber: "Q-2024-008",
    accountName: "Harmony Health",
    contactName: "Christopher Lee",
    status: "Pending",
    totalAmount: 7250.00,
    validUntil: "2024-12-10",
    createdDate: "2024-11-19",
    description: "Weekly Restock - High Demand Items",
    lineItemCount: 5,
    opportunityName: "Weekly Restock Nov"
  },
  {
    id: "9",
    quoteNumber: "Q-2024-009",
    accountName: "Pure Wellness Market",
    contactName: "Emily White",
    status: "Draft",
    totalAmount: 13400.00,
    validUntil: "2024-12-22",
    createdDate: "2024-11-21",
    description: "Concentrates & Vapes Expansion",
    lineItemCount: 9,
    opportunityName: "Product Line Expansion"
  },
  {
    id: "10",
    quoteNumber: "Q-2024-010",
    accountName: "Green Leaf Collective",
    contactName: "James Wilson",
    status: "Approved",
    totalAmount: 16750.25,
    validUntil: "2024-12-30",
    createdDate: "2024-11-17",
    description: "Multi-Location Stock - 3 Stores",
    lineItemCount: 18,
    opportunityName: "Multi-Store Order Q4"
  },
  {
    id: "11",
    quoteNumber: "Q-2024-011",
    accountName: "Elevated Dispensary",
    contactName: "Patricia Brown",
    status: "Pending",
    totalAmount: 9100.75,
    validUntil: "2024-12-12",
    createdDate: "2024-11-16",
    description: "Premium Pre-Roll Collection",
    lineItemCount: 6,
    opportunityName: "Premium Line Launch"
  },
  {
    id: "12",
    quoteNumber: "Q-2024-012",
    accountName: "Coastal Cannabis Co.",
    contactName: "Daniel Moore",
    status: "Converted",
    totalAmount: 14200.00,
    validUntil: "2024-11-28",
    createdDate: "2024-10-25",
    description: "Bulk Order - Edibles & Concentrates",
    lineItemCount: 10,
    opportunityName: "Bulk Purchase Oct"
  },
  {
    id: "13",
    quoteNumber: "Q-2024-013",
    accountName: "Mountain View Wellness",
    contactName: "Karen Davis",
    status: "Draft",
    totalAmount: 6800.50,
    validUntil: "2024-12-18",
    createdDate: "2024-11-20",
    description: "New Product Trial - Topicals",
    lineItemCount: 4,
    opportunityName: "Topicals Trial"
  },
  {
    id: "14",
    quoteNumber: "Q-2024-014",
    accountName: "Sunset Remedies",
    contactName: "Steven Garcia",
    status: "Approved",
    totalAmount: 19500.00,
    validUntil: "2024-12-29",
    createdDate: "2024-11-14",
    description: "Holiday Special - Premium Selection",
    lineItemCount: 14,
    opportunityName: "Holiday Premium 2024"
  },
  {
    id: "15",
    quoteNumber: "Q-2024-015",
    accountName: "Organic Options",
    contactName: "Michelle Rodriguez",
    status: "Pending",
    totalAmount: 10300.25,
    validUntil: "2024-12-16",
    createdDate: "2024-11-19",
    description: "Organic Flower Collection",
    lineItemCount: 7,
    opportunityName: "Organic Line Q4"
  },
  {
    id: "16",
    quoteNumber: "Q-2024-016",
    accountName: "Valley Green Dispensary",
    contactName: "Thomas Martinez",
    status: "Expired",
    totalAmount: 8500.00,
    validUntil: "2024-11-20",
    createdDate: "2024-10-10",
    description: "October Special Order",
    lineItemCount: 6,
    opportunityName: "October Specials"
  },
  {
    id: "17",
    quoteNumber: "Q-2024-017",
    accountName: "Pacific Wellness Group",
    contactName: "Jennifer Lopez",
    status: "Draft",
    totalAmount: 12900.00,
    validUntil: "2024-12-25",
    createdDate: "2024-11-21",
    description: "Group Order - 4 Locations",
    lineItemCount: 16,
    opportunityName: "Group Purchase Q4"
  },
  {
    id: "18",
    quoteNumber: "Q-2024-018",
    accountName: "Healing Gardens",
    contactName: "Brian Taylor",
    status: "Approved",
    totalAmount: 11750.50,
    validUntil: "2024-12-27",
    createdDate: "2024-11-16",
    description: "Concentrates Expansion Pack",
    lineItemCount: 8,
    opportunityName: "Concentrates Focus"
  },
  {
    id: "19",
    quoteNumber: "Q-2024-019",
    accountName: "Verde Solutions",
    contactName: "Angela Harris",
    status: "Pending",
    totalAmount: 7900.00,
    validUntil: "2024-12-14",
    createdDate: "2024-11-18",
    description: "Monthly Subscription - December",
    lineItemCount: 5,
    opportunityName: "Monthly Sub Dec"
  },
  {
    id: "20",
    quoteNumber: "Q-2024-020",
    accountName: "Emerald Collective",
    contactName: "Mark Thompson",
    status: "Converted",
    totalAmount: 17250.75,
    validUntil: "2024-11-29",
    createdDate: "2024-10-22",
    description: "Full Product Line Restock",
    lineItemCount: 13,
    opportunityName: "Full Line Restock Nov"
  }
];

export const mockQuoteStats: QuoteStats = {
  totalQuotes: 20,
  pendingQuotes: 5,
  approvedQuotes: 5,
  totalValue: 237350.00
};
